stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

before_script:
  - npm install --save-dev

build_job:
  stage: build
  script:
    - npm run build
  only:
    - master
  tags:
    - master

test_job:
  stage: test
  script:
    - npm run test-cov
  tags:
    - master
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

deploy_job:
  stage: deploy
  script:
    - npm run build
    - npm publish
  only:
    - tags
  tags:
    - master
